version: "2"
plugins:
  editorconfig:
    enabled: true
  fixme:
    enabled: true
  git-legal:
    enabled: true
  markdownlint:
    enabled: true
  shellcheck:
    enabled: true
  tslint:
    enabled: true
    config: tslint.json
exclude_patterns:
  - ".idea/"
  - ".nuxt/"
  - ".nyc_output/"
  - ".vscode/"
  - "apidoc/"
  - "build/"
  - "coverage/"
  # Default
  - "config/"
  - "db/"
  - "dist/"
  - "features/"
  - "**/node_modules/"
  - "script/"
  - "**/spec/"
  - "**/test/"
  - "**/tests/"
  - "Tests/"
  - "**/vendor/"
  - "**/*_test.go"
  - "**/*.d.ts"
