version: '3'

services:
  web:
    build:
      context: ../
      dockerfile: docker/web/Dockerfile
    restart: "${COMPOSE_RESTART}"
    ports:
      - "${WEB_PORT}:80"
    env_file:
      - web/.env
    depends_on:
      - postgres
      - redis
      - rabbitmq
      - s3proxy
      - mail
  mail:
    image: analogic/poste.io:2
    hostname: "${MAIL_HOSTNAME}"
    dns: dns-mailoop
    restart: "${COMPOSE_RESTART}"
    ports:
      - "${MAIL_PORT_WEB}:80"
    environment:
      HTTPS: 'OFF'
      DISABLE_CLAMAV: 'TRUE'
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - "${MAIL_VOLUME}:/data"
    depends_on:
      - dns-mailoop
  dns-mailoop:
    build:
      context: dns-mailoop
      dockerfile: Dockerfile
    restart: "${COMPOSE_RESTART}"
    environment:
      LOOP: "${MAIL_HOSTNAME}"
